-- Toda Query termina com ;

/*
DUAS FORMAS DE EXECUÇÃO DAS QUERIES:
1) COMO INSTRUÇÃO - GERAR UM RESULTADO EM FORMA DE TABELA
2) COMO SCRIPT - GERAR RESULTADO EM TEXTO
*/
SELECT * -- * indica que a query irá trazer todas as colunas da tabela
FROM EMP;

SELECT FIRST_NAME FROM EMP;

/*
SELECT -- PROJETA AS COLUNAS DESEJADAS EXISTENTES NA ORIGEM FROM
FROM -- RELACIONA A ORIGEM ONDE ESTÃO OS DADOS A SEREM CONSULTADOS
WHERE -- FAZ A RESTRIÇÃO (FILTRO) DAS LINHAS A SEREM MOSTRADAS CONFORME UMA CONDIÇÃO
      -- OPERADORES PARA DEFINIR UMA CONDIÇÃO: =, <>, (!=), >=, <=, >, <, NOT, AND, OR
      --                                                     BETWEEN, LIKE, IN
GROUP BY -- ESTABELECER SUBGRUPOS NO RESULTADO DA QUERY
HAVING -- FAZ A RESTRIÇÃO (FILTRO) OS SUBGRUPOS FORMADOS CONFORME UMA CONDIÇÃO
ORDER BY -- ORDENAR O RESULTADO APRESENTADO, ASCENDENTE OU DESCENDENTE POR COLUNAS
*/

-- PRODUZINDO RESULTADOS CONSTANTES A PARTIR DE UMA TABELA COM DADOS NO BD
SELECT 1234234234234    /   3452345324 AS CALC1,
        TO_CHAR(SYSDATE, 'YYYY-DD-MM') DATA_HOJE,
        'Teste' AS STRING,
        TO_CHAR(5) AS NUMERO,
        FIRST_NAME PRIMEIRO_NOME
FROM EMP;

-- VERIFICANDO E ANALISANDO METADADOS NO DICIONÁRIO DE DADOS DINÂMICO (CATÁLOGO)
DESC ALL_OBJECTS; -- DESC DESCREVE A ESTRUTURA DE UMA TABELA OU VIEW