-- CRIAÇÃO DE TABELAS
CREATE TABLE ALUNO (
    RA NUMBER,
    NOME VARCHAR(40),
    IDADE NUMBER,
    TURMA CHAR(1)
);

-- ADIÇÃO DE CONSTRAINTS
ALTER TABLE ALUNO ADD CONSTRAINT RA_UNIQUE UNIQUE (RA);

-- INSERÇÃO DE LINHA NA TABELA
INSERT INTO ALUNO (RA, NOME, IDADE, TURMA) VALUES (22301150, 'MARCOS', 19, 'A');

-- CONSULTA DE TODOS OS ELEMENTOS DA TABELA
SELECT * FROM ALUNO;

-- CONSULTA DE COLUNAS ESPECÍFICAS NA TABELA

SELECT RA, NOME FROM ALUNO;

INSERT INTO ALUNO (RA, NOME, IDADE, TURMA) VALUES (22302230, 'PEDRO', 19, 'A');

INSERT INTO ALUNO (RA, NOME, IDADE, TURMA) VALUES (22302130, 'KAYNAN', 47, 'B');

-- CONSULTA DE DADOS ESPECÍFICOS
SELECT * FROM ALUNO WHERE TURMA = 'A';

-- INSERÇÃO DE CONDIÇÃO EM UMA COLUNA DA TABELA
ALTER TABLE ALUNO ADD CONSTRAINT IDADE_CHK CHECK (IDADE > 10);

-- APÓS A IMPOSIÇÃO DA CONDIÇÃO, NÃO É POSSÍVEL ADICIONAR ALUNOS COM MENOS DE 10 ANOS. LOGO O COMANDO ABAIXO DA ERRO
INSERT INTO ALUNO (RA, NOME, IDADE, TURMA) VALUES (22402240, 'JOELSON', 9, 'C');

-- ADIÇÃO DE COLUNA NA TABELA
ALTER TABLE ALUNO ADD FEIO CHAR(1);

-- FUNÇÃO QUE CONSULTA O BANCO DE DADOS E O ORDENA CRESCENTEMENTE POR UMA COLUNA ESPECÍFICA
SELECT * FROM ALUNO ORDER BY RA;

-- MESMA COISA MAIS ORDENA DECRESCENTE
SELECT * FROM ALUNO ORDER BY RA DESC;

-- CONTA O NUMERO DE ALUNOS CADASTRADOS
SELECT COUNT(NOME) FROM ALUNO;

-- CONTA QUANTAS IDADES DIFERENTES ESTÃO CADASTRADAS NO B.D.
SELECT COUNT(DISTINCT IDADE) FROM ALUNO;

-- TRAZ A SOMA DAS IDADES DE TODOS OS ALUNOS CADASTRADOS
SELECT SUM(IDADE) FROM ALUNO;

-- TRAZ A MEDIA DAS IDADES DE TODOS OS ALUNOS CADASTRADOS
SELECT AVG(IDADE) FROM ALUNO;

-- TRAZ A IDADE MINIMA CADASTRADA
SELECT MIN(IDADE) FROM ALUNO;

-- TRAZ O MAIOR RA CADASTRADO FAZENDO O NOME DA TABELA VIRAR MATRICULA NO RESULTADO
SELECT MAX(RA) AS MATRICULA FROM ALUNO;